#!/usr/bin/env python3
"""Generate the include file without duplicating local proxy groups."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def build():
    source = (ROOT / "Shadowrocket.conf").read_text()
    source = re.sub(r"(?ms)^\[Proxy Group\]\n.*?(?=^\[Rule\]\n)", "", source)
    source = source.replace("/main/Shadowrocket.conf", "/main/Rules.conf")
    (ROOT / "Rules.conf").write_text("# Generated by scripts/build_rules.py; edit Shadowrocket.conf.\n" + source)


if __name__ == "__main__":
    build()
    print("Generated Rules.conf without proxy group definitions")
